version: '3.8'

services:
  voice-app:
    build: .
    container_name: python_app_container
    ports:
      - "6644:6644"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "main.py"]
